"""add teacher_branch table

Revision ID: 92ac03a71db0
Revises: f88aa90d309d
Create Date: 2025-12-27 13:50:15.686406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ac03a71db0'
down_revision: Union[str, Sequence[str], None] = 'f88aa90d309d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_branch',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'branch_id')
    )
    op.drop_constraint(op.f('teachers_branch_id_fkey'), 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('teachers_branch_id_fkey'), 'teachers', 'branches', ['branch_id'], ['id'])
    op.drop_table('teacher_branch')
    # ### end Alembic commands ###
